# Generated by Django 4.1.7 on 2023-03-27 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('form', models.FileField(upload_to='files/')),
            ],
        ),
    ]
