# Generated by Django 4.1.7 on 2023-03-27 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='category',
            field=models.CharField(default='Umbrella', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='submissionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 1, 2, 7, 59051)),
        ),
    ]
