# Generated by Django 4.1.7 on 2023-03-27 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verification_category_verification_submissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verification',
            name='submissionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 2, 22, 55, 326089)),
        ),
    ]
