# Generated by Django 4.1.7 on 2023-03-27 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verification_ischecked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='submissionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 17, 30, 48, 140935)),
        ),
    ]
