# Generated by Django 4.1.7 on 2023-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLost', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('locationFound', models.CharField(max_length=100)),
                ('dateFound', models.DateField()),
                ('timeFound', models.TimeField()),
            ],
        ),
    ]
