# Generated by Django 4.2 on 2023-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_tree_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='harvestDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
