# Generated by Django 4.1.7 on 2023-03-13 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_num', models.IntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
                ('administrator', models.BooleanField(default=False)),
            ],
        ),
    ]
