# Generated by Django 4.1.7 on 2023-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_assignment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assignment_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/pictures'),
        ),
    ]
