# Generated by Django 4.1.7 on 2023-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_assignment_image_item_lost_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lost_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='lostItems'),
        ),
    ]
